### ISSUE TITLE
Dragon Fire

### ISSUE THREAD

**Issue by RayBlazar** [MoriyaShiine/realistic-fire-spread#1]
### Mod version

1.12

### A description of the issue

Dragons seems to cause a crash. Sorry I don't got specific info, Ice and Fire dragons breath causes a crash listing this mod.

**Comment by MoriyaShiine** [comment]
1.12 has been unsupported for 3 years, but if you send a log/crash report I can maybe look at it

**Comment by RayBlazar** [comment]
Oh my bad, didn't even think of that. I'll do that sometime. I removed it from my little pack awhile back but I was messing around with fire recently and thought fire mechanics are weird, so I wanted it back if possible.
