### ISSUE TITLE
Console spam after removing

### ISSUE THREAD

**Issue by sternschnaube** [MoriyaShiine/realistic-fire-spread#3]
### Mod version

1.19.3

### A description of the issue

Hello, after removing the mod I encounter this log spam:

[Server thread/WARN]: Failed to deserialize component: unregistered key realisticfirespread:fire_from_sun
[Server thread/WARN]: Failed to deserialize component: unregistered key realisticfirespread:fire_from_sun
[Server thread/WARN]: Failed to deserialize component: unregistered key realisticfirespread:fire_from_sun
[Server thread/WARN]: Failed to deserialize component: unregistered key realisticfirespread:fire_from_sun
[Server thread/WARN]: Failed to deserialize component: unregistered key realisticfirespread:fire_from_sun
[Server thread/WARN]: Failed to deserialize component: unregistered key realisticfirespread:fire_from_sun
[Server thread/WARN]: Failed to deserialize component: unregistered key realisticfirespread:fire_from_sun
[Server thread/WARN]: Failed to deserialize component: unregistered key realisticfirespread:fire_from_sun
[Server thread/WARN]: Failed to deserialize component: unregistered key realisticfirespread:fire_from_sun

### Log or crash report

/

**Comment by MoriyaShiine** [comment]
This is expected and there's nothing I can do about it. It should only run once per entity so it'll eventually go away, but generally removing mods that use CCA are going to do that

**Comment by venaminecraft** [comment]
Oki interesting, thanks for the fast answer.
